server:
  port: 8085

spring:
  application:
    name: cards-app
  datasource:
    url: "jdbc:postgresql://localhost:5432/cards"
    username: "postgres"
    password: "12345"
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

timezone:
  location:
    bogota: "America/Bogota"